# Cloneset with nginx

apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
metadata:
  name: cam-cloneset
  namespace: default
  labels:
    app: nginx-cloneset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-cloneset
  template:
    metadata:
      labels:
        app: nginx-cloneset
    spec: 
      containers:
      - name: cam-cloneset-nginx
        image: nginx:alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 50Mi
          limits:
            memory: 100Mi
      restartPolicy: Always
      hostname: nginx
      nodeSelector:
        kubernetes.io/os: linux
