apiVersion: v1
kind: Pod
metadata:
  name: nginx-alp-with-pv
  namespace: skad
  labels:
    cam: nginx-alpine
  annotations:
    author: cameda
spec:
  containers:
  - image: nginx:1.24.0-alpine
    imagePullPolicy: IfNotPresent
    name: nginx-alpine
    resources:
      requests:
        cpu: 10m
        memory: 20Mi
      limits:
        cpu: 15m
        memory: 30Mi
    readinessProbe:
      periodSeconds: 5
      initialDelaySeconds: 10
      successThreshold: 1
      failureThreshold: 5
      httpGet:
        path: /
        port: 80
    ports:
    - containerPort: 80
    - containerPort: 443
    volumeMounts:
    - name: cam-mnt
      mountPath: "/mnt"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: cam-mnt
    persistentVolumeClaim:
      claimName: cam-pvc
