# Pod with nginx alpine.
apiVersion: v1
kind: Pod
metadata:
  name: cam-pod-nginx
  namespace: default
  labels:
    cam: nginx
  annotations:
    author: cameda
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "50m"
        memory: "50Mi"
      limits:
        memory: "100Mi"
    ports:
    - containerPort: 80
  restartPolicy: OnFailure
  hostname: nginx
  nodeSelector:
    kubernetes.io/os: linux
