# Создаём приоритет чуть выше дефолтного. Который равен нулю. 
# Поды с меньшим приоритетом будут принудительно выселяться. 

apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: cam-pc
  namespace: default
  labels:
    pc: main
  annotations:
    author: cameda
value: 200
globalDefault: false
description: "PC with preemption"
