apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: internal-policy
  namespace: default
spec:
  policyTypes:
  - Ingress
  - Egress
  podSelector:
    matchLabels:
      cam: master
  ingress:
  - from:
    - ipBlock:
        cidr: 10.143.0.15/32
    ports:
    - protocol: TCP
      port: 6443
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
  egress:
  - to:
    - ipBlock:
        cidr: 10.143.0.15/32
    ports:
    - protocol: TCP
      port: 6443
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
