apiVersion: v1
kind: PersistentVolume
metadata:
  name: cam-pv
  labels:
    pv: hostpath
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt"
  claimRef:
    name: cam-pvc
    namespace: skad
