apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cam-pvc
  namespace: skad
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
