apiVersion: v1
kind: LimitRange
metadata:
  name: cam-limits
  namespace: default
  labels:
    limit: pod
    environment: prod
  annotations:
    author: cameda
spec:
  limits:
  - type: Pod
    default: # this section defines default limits
      cpu: 500m
    defaultRequest: # this section defines default requests
      cpu: 500m
    min:
      cpu: 100m
      memory: 100Mi
    max:
      cpu: "1"
      memory: 800Mi
  - type: Container
    default: # this section defines default limits
      cpu: 500m
    defaultRequest: # this section defines default requests
      cpu: 500m
    max: # max and min define the limit range
      cpu: "1"
    min:
      cpu: 100m
