# Изменить настройки для net.core.somaxconn в sysctl.
# Посмотреть текущие значения sysctl -a
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: set-sysctl
  namespace: default
  labels:
    env: test
  annotations:
    author: cameda
spec:
  selector:
    matchLabels:
      app: set-sysctl
  template:
    metadata:
      labels:
        app: set-sysctl
    spec:
      containers:
      - name: set-sysctl
        image: amouat/network-utils
        command: ["sh", "-c"]
        args:
        - |
          sysctl -w net.core.somaxconn=2048 && sleep 24h
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "200m"
            memory: "100Mi"
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
