# Сервис с дефолтным типом - ClusterIP. Обрабатывает трафик с двух портов.
# Следит за подами с меткой app: nginx.

apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: nginx-svc-clusterip
  labels:
    environment: test
  annotations:
    author: cameda
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
  - name: http
    protocol: TCP
    port: 80
  - name: https
    protocol: TCP
    port: 443
