# Сервис типа NodePort. Следит за подами с меткой app: nginx
# Обрабатывает трафик с двух портов.

apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: nginx-svc-nodeport-2ports
  labels:
    environment: test
  annotations:
    author: cameda
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - name: http
    protocol: TCP
    port: 80
    nodePort: 30012
  - name: https
    protocol: TCP
    port: 443
    nodePort: 30013
