# Сервис типа NodePort. Следит за подами с меткой app: nginx
# Обрабатывает трафик с двух портов.
# Включена политика обработки трафика Local. Включены сессии.

apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: nginx-svc-with-affinity-nodeport
  labels:
    environment: prod
  annotations:
    author: cameda
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30010
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
    nodePort: 30011
  externalTrafficPolicy: Local
  sessionAffinity: ClientIP
