apiVersion: v1
kind: Secret
metadata:
  name: postgresql
  namespace: crossplane
type: Opaque
data:
  # ghbrjk
  password: Z2hicmprCg==
---
apiVersion: mdb.yandex-cloud.jet.crossplane.io/v1alpha1
kind: PostgresqlCluster
metadata:
  annotations:
    uptest.upbound.io/conditions: 'Ready,Synced'
    uptest.upbound.io/pre-delete-hook: testhooks/delete-postgres-deps.sh
  name: cam-pg1
  namespace: crossplane
spec:
  forProvider:
    name: cam-postgresql
    environment: PRESTABLE
    networkIdRef:
      name: cameda-practicum
    config:
      - version: "17"
        resources:
          - diskSize: 33
            diskTypeId: network-ssd
            resourcePresetId: s3-c2-m8
        postgresqlConfig:
          max_connections: "395"
          enable_parallel_hash: "true"
          vacuum_cleanup_index_scale_factor: "0.2"
          autovacuum_vacuum_scale_factor: "0.34"
          default_transaction_isolation: "TRANSACTION_ISOLATION_READ_COMMITTED"
          shared_preload_libraries: SHARED_PRELOAD_LIBRARIES_AUTO_EXPLAIN
    maintenanceWindow:
      - type: WEEKLY
        day: SAT
        hour: 12
    host:
      - zone: ru-central1-d
        subnetIdRef:
          id: fl8bd3gnjj2q66ir5cts
  providerConfigRef:
    name: default
  writeConnectionSecretToRef:
    name: postgress-conn
    namespace: crossplane
---
apiVersion: mdb.yandex-cloud.jet.crossplane.io/v1alpha1
kind: PostgresqlUser
metadata:
  annotations:
    meta.upbound.io/example-id: mdb/v1alpha1/postgresqluser
  labels:
    testing.upbound.io/example-name: postgres
  name: pg-user1
  namespace: crossplane
spec:
  forProvider:
    clusterIdRef:
      name: cam-postgresql
    connLimit: 50
    name: cameda
    passwordSecretRef:
      name: cameda
      key: ghbrjk2
      namespace: default
    permission:
    settings:
      default_transaction_isolation: "read committed"
      log_min_duration_statement: "5000"
  providerConfigRef:
    name: crossplane-config
    namespace: crossplane
---
apiVersion: mdb.yandex-cloud.jet.crossplane.io/v1alpha1
kind: PostgresqlDatabase
metadata:
  annotations:
    meta.upbound.io/example-id: mdb/v1alpha1/postgresqldatabase
  labels:
    testing.upbound.io/example-name: postgres
  name: pg-database1
  namespace: crossplane
spec:
  forProvider:
    clusterIdRef:
      name: example-pg
    extension:
    - name: uuid-ossp
    - name: xml2
    lcCollate: en_US.UTF-8
    lcType: en_US.UTF-8
    name: db_name
    owner: user1
  providerConfigRef:
    name: crossplane-config
    namespace: crossplane
