apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dhclient-restart
  labels:
    environment: test
    k8s-app: dhclient
  annotations:
    author: cameda
spec:
  selector:
    matchLabels:
      app: dhclient
  template:
    metadata:
      labels:
        app: dhclient
    spec:
      containers:
      - name: dhclient
        image: busybox
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 50Mi
          requests:
            cpu: 70m
            memory: 50Mi
        command:
        - /bin/sh
        - -c
        - |
          while true; do
            sudo dhclient -v -r
            sudo dhclient
            sleep infinity
          done
        securityContext:
          privileged: true
      hostPID: true
      hostIPC: true
      hostNetwork: true
      hostname: dhclient
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      nodeSelector:
        kubernetes.io/os: linux
