apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: set-mtu
  namespace: default
  labels:
    env: test
  annotations:
    author: cameda
spec:
  selector:
    matchLabels:
      app: set-mtu
  template:
    metadata:
      labels:
        app: set-mtu
    spec:
      containers:
      - name: set-mtu
        image: amouat/network-utils
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c"]
        args:
        - |
          ip link set dev eth0 mtu 1450 && sleep 24h
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "200m"
            memory: "100Mi"
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
