apiVersion: v1
kind: Pod
metadata:
  name: check-dns
  namespace: default
  labels:
    env: test
  annotations:
    author: cameda
spec:
  containers:
  - name: check-dns
    image: k8s.gcr.io/jessie-dnsutils
    command: ["/bin/sh"]
    args: ["-c", "sleep 1d"]
  restartPolicy: Never
