apiVersion: v1
kind: Pod
metadata:
  name: cam-hostnetwork-pod
  namespace: default
  labels:
    app: nginx
    environment: test
  annotations:
    author: cameda
spec:
  containers:
  - name: cam-hostnetwork-container
    image: nginx:alpine
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
    - containerPort: 443
    resources:
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        memory: 80Mi
  restartPolicy: Always
  hostname: nginx
  subdomain: web
  hostNetwork: true
