# Pod with hostPath.
apiVersion: v1
kind: Pod
metadata:
  name: cam-pod-ubuntu
  namespace: default
  labels:
    cam: ubuntu
  annotations:
    author: cameda
spec:
  containers:
  - name: cam-container-ubuntu
    image: ubuntu
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "1"
        memory: "1G"
      limits:
        memory: "2G"
    command: ["sh", "-c"]
    args: ["sleep 24h"]
  restartPolicy: OnFailure
  hostname: cam-ubuntu
  nodeSelector:
    kubernetes.io/os: linux
