apiVersion: v1
kind: Pod
metadata:
  name: cam-ubuntu
  namespace: default
  labels:
    environment: test
    app: ubuntu
  annotations:
    author: cameda
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["/bin/sleep", "3650d"]
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
