# Pod for check dns.
apiVersion: v1
kind: Pod
metadata:
  name: check-dns
  namespace: default
  labels:
    env: test
  annotations:
    author: cameda
spec:
  containers:
  - name: check-dns
    image: k8s.gcr.io/jessie-dnsutils
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "100m"
        memory: "150Mi"
      limits:
        memory: "200Mi"
    command: ["/bin/sh"]
    args: ["-c", "sleep 1d"]
  restartPolicy: Never
  hostname: check-dns
  nodeSelector:
    kubernetes.io/os: linux
