# Pod with hostPath.
apiVersion: v1
kind: Pod
metadata:
  name: cam-pod-busybox
  namespace: default
  labels:
    cam: busybox
  annotations:
    author: cameda
spec:
  containers:
  - name: busybox
    image: busybox
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "100m"
        memory: "120Mi"
      limits:
        memory: "200Mi"
    command: ["sh", "-c"]
    args: ["sleep 24h"]
    livenessProbe:
      failureThreshold: 10
      successThreshold: 1
      httpGet:
        path: /
        port: 80
      periodSeconds: 10
      timeoutSeconds: 1
      initialDelaySeconds: 5
  restartPolicy: OnFailure
  hostname: busybox
  nodeSelector:
    kubernetes.io/os: linux
