apiVersion: v1
kind: Pod
metadata:
  name: cam-pod-for-test
  namespace: default
  labels:
    environment: test
    app: test
  annotations:
    author: cameda
spec:
  containers:
  - name: cam-container-for-test
    image: amouat/network-utils
    command: ["/bin/sleep", "3650d"]
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
