# Deployment with Nginx

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cam-deploy-nginx
  namespace: default
  labels:
    app: deploy-nginx
    environment: test
  annotations:
    author: cameda
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cam-deploy-nginx
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cam-deploy-nginx
    spec:
      containers:
      - name: cam-deploy-nginx
        image: nginx:alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            memory: 100Mi
      restartPolicy: Always
      hostname: nginx
      nodeSelector:
        kubernetes.io/os: linux
